// <auto-generated />
using System;
using Assignment1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240225161649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment1.Models.CarRental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("CarId");

                    b.ToTable("CarRentals");
                });

            modelBuilder.Entity("Assignment1.Models.Cars", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "Honda",
                            IsAvailable = true,
                            Model = "Civic Sport",
                            PricePerDay = 69.989999999999995,
                            Year = 2019
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Toyota",
                            IsAvailable = true,
                            Model = "Camry SE",
                            PricePerDay = 79.989999999999995,
                            Year = 2020
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "Ford",
                            IsAvailable = true,
                            Model = "Mustang GT",
                            PricePerDay = 99.989999999999995,
                            Year = 2018
                        },
                        new
                        {
                            CarId = 4,
                            Brand = "Chevrolet",
                            IsAvailable = true,
                            Model = "Camaro SS",
                            PricePerDay = 109.98999999999999,
                            Year = 2021
                        },
                        new
                        {
                            CarId = 5,
                            Brand = "Nissan",
                            IsAvailable = true,
                            Model = "Altima SV",
                            PricePerDay = 74.989999999999995,
                            Year = 2020
                        },
                        new
                        {
                            CarId = 6,
                            Brand = "Hyundai",
                            IsAvailable = true,
                            Model = "Sonata Limited",
                            PricePerDay = 69.989999999999995,
                            Year = 2019
                        },
                        new
                        {
                            CarId = 7,
                            Brand = "Kia",
                            IsAvailable = true,
                            Model = "Optima EX",
                            PricePerDay = 64.989999999999995,
                            Year = 2018
                        },
                        new
                        {
                            CarId = 8,
                            Brand = "BMW",
                            IsAvailable = true,
                            Model = "3 Series",
                            PricePerDay = 129.99000000000001,
                            Year = 2020
                        },
                        new
                        {
                            CarId = 9,
                            Brand = "Mercedes-Benz",
                            IsAvailable = true,
                            Model = "C-Class",
                            PricePerDay = 139.99000000000001,
                            Year = 2021
                        },
                        new
                        {
                            CarId = 10,
                            Brand = "Audi",
                            IsAvailable = true,
                            Model = "A4 Premium",
                            PricePerDay = 119.98999999999999,
                            Year = 2019
                        });
                });

            modelBuilder.Entity("Assignment1.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("FlightId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            Airline = "Delta Airlines",
                            ArrivalAirport = "JFK",
                            ArrivalTime = new DateTime(2024, 3, 15, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "LAX",
                            DepartureTime = new DateTime(2024, 3, 15, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Destination = "New York",
                            Price = 350.00m
                        },
                        new
                        {
                            FlightId = 2,
                            Airline = "American Airlines",
                            ArrivalAirport = "ORD",
                            ArrivalTime = new DateTime(2024, 3, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "MIA",
                            DepartureTime = new DateTime(2024, 3, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Chicago",
                            Price = 280.00m
                        },
                        new
                        {
                            FlightId = 3,
                            Airline = "United Airlines",
                            ArrivalAirport = "SFO",
                            ArrivalTime = new DateTime(2024, 4, 5, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "JFK",
                            DepartureTime = new DateTime(2024, 4, 5, 6, 45, 0, 0, DateTimeKind.Unspecified),
                            Destination = "San Francisco",
                            Price = 400.00m
                        },
                        new
                        {
                            FlightId = 4,
                            Airline = "Southwest Airlines",
                            ArrivalAirport = "LAS",
                            ArrivalTime = new DateTime(2024, 4, 10, 12, 50, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "DEN",
                            DepartureTime = new DateTime(2024, 4, 10, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Las Vegas",
                            Price = 150.00m
                        },
                        new
                        {
                            FlightId = 5,
                            Airline = "JetBlue",
                            ArrivalAirport = "BOS",
                            ArrivalTime = new DateTime(2024, 4, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "FLL",
                            DepartureTime = new DateTime(2024, 4, 15, 5, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Boston",
                            Price = 200.00m
                        },
                        new
                        {
                            FlightId = 6,
                            Airline = "Alaska Airlines",
                            ArrivalAirport = "SEA",
                            ArrivalTime = new DateTime(2024, 4, 20, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "LAX",
                            DepartureTime = new DateTime(2024, 4, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Seattle",
                            Price = 220.00m
                        },
                        new
                        {
                            FlightId = 7,
                            Airline = "Spirit Airlines",
                            ArrivalAirport = "DFW",
                            ArrivalTime = new DateTime(2024, 5, 1, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "ATL",
                            DepartureTime = new DateTime(2024, 5, 1, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Dallas",
                            Price = 95.00m
                        },
                        new
                        {
                            FlightId = 8,
                            Airline = "Frontier Airlines",
                            ArrivalAirport = "DEN",
                            ArrivalTime = new DateTime(2024, 5, 10, 20, 35, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "PHX",
                            DepartureTime = new DateTime(2024, 5, 10, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Denver",
                            Price = 115.00m
                        },
                        new
                        {
                            FlightId = 9,
                            Airline = "Hawaiian Airlines",
                            ArrivalAirport = "HNL",
                            ArrivalTime = new DateTime(2024, 5, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "LAX",
                            DepartureTime = new DateTime(2024, 5, 15, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "Honolulu",
                            Price = 500.00m
                        },
                        new
                        {
                            FlightId = 10,
                            Airline = "British Airways",
                            ArrivalAirport = "LHR",
                            ArrivalTime = new DateTime(2024, 6, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureAirport = "JFK",
                            DepartureTime = new DateTime(2024, 6, 1, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Destination = "London",
                            Price = 750.00m
                        });
                });

            modelBuilder.Entity("Assignment1.Models.FlightBooking", b =>
                {
                    b.Property<int>("FlightBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightBookingId"));

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("FlightBookingId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightBookings");
                });

            modelBuilder.Entity("Assignment1.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerNight")
                        .HasColumnType("float");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelId = 1,
                            Amenities = "Yes",
                            Location = "Manhattan, New York",
                            Name = "The Ritz Carlton",
                            PricePerNight = 1139.0,
                            ServiceType = "Full Service"
                        },
                        new
                        {
                            HotelId = 2,
                            Amenities = "Yes",
                            Location = "Manhattan, New York",
                            Name = "The Plaza Hotel",
                            PricePerNight = 1780.0,
                            ServiceType = "Full Service"
                        },
                        new
                        {
                            HotelId = 4,
                            Amenities = "Yes",
                            Location = "Paris, France",
                            Name = "Hotel Louvre Sainte Anne",
                            PricePerNight = 291.0,
                            ServiceType = "Full Service"
                        },
                        new
                        {
                            HotelId = 5,
                            Amenities = "Yes",
                            Location = "Paris, France",
                            Name = "Hotel Brighton",
                            PricePerNight = 509.0,
                            ServiceType = "Full Service"
                        },
                        new
                        {
                            HotelId = 6,
                            Amenities = "Yes",
                            Location = "Paris, France",
                            Name = "Solly Hotel Paris",
                            PricePerNight = 383.0,
                            ServiceType = "Full Service"
                        },
                        new
                        {
                            HotelId = 7,
                            Amenities = "Yes",
                            Location = "Tokyo, Japan",
                            Name = "Grand Hyatt Tokyo",
                            PricePerNight = 987.0,
                            ServiceType = "Full Service"
                        },
                        new
                        {
                            HotelId = 8,
                            Amenities = "Yes",
                            Location = "Tokyo, Japan",
                            Name = "The Prince Park Tower",
                            PricePerNight = 484.0,
                            ServiceType = "Full Service"
                        },
                        new
                        {
                            HotelId = 9,
                            Amenities = "Yes",
                            Location = "Tokyo, Japan",
                            Name = "Four Seasons Hotel Tokyo",
                            PricePerNight = 1104.0,
                            ServiceType = "Full Service"
                        });
                });

            modelBuilder.Entity("Assignment1.Models.CarRental", b =>
                {
                    b.HasOne("Assignment1.Models.Cars", "Car")
                        .WithMany("CarRentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("Assignment1.Models.FlightBooking", b =>
                {
                    b.HasOne("Assignment1.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("Assignment1.Models.Cars", b =>
                {
                    b.Navigation("CarRentals");
                });
#pragma warning restore 612, 618
        }
    }
}
